config/routes.rb
Todo::Application.routes.draw do 

  resources :categories

  resources :subcategories

  resources :expense_journals

  root :to => "home#index"
  match 'users/activateuser/:id', :to => 'users#activateuser'
  match '/users/:id/reset',  :to => 'users#updatepasswordreset'
  match '/signup/users/check_email', :to => 'users#check_email'
  match '/signup/users/check_name', :to => 'users#check_name'
  resources :users 
  resources :sessions, :only => [:new, :create, :destroy]
  get "sessions/new"
  match '/signup',  :to => 'users#new'
  match '/MailPasswordRequest',  :to => 'users#MailPasswordRequest'
  match '/MailPassword',  :to => 'users#MailPassword'
  match 'MailPassword/ResetPasswordRequest/:encryptedhash', :to => 'users#ResetPasswordRequest'
  match '/ResetPassword',  :to => 'users#ResetPassword'
  match '/ChangePasswordRequest',  :to => 'users#ChangePasswordRequest'
  match '/ChangePassword',  :to => 'users#ChangePassword'
  match '/DownloadMobile', :to => 'users#DownloadMobile'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/MapRequest',  :to => 'places#MapRequest'
  match '/MapOfPlace',  :to => 'places#MapOfPlace'
  match 'tasks/show',  :to => 'tasks#show'
  match 'tasks/show1',  :to => 'tasks#show1'
  match 'tasks/destroy',  :to => 'tasks#destroy'
  match '/signup/users/check_name', :to => 'users#check_name'
  match 'tasks/check_date_due', :to => 'tasks#check_date_due'
  match '/tasks/retrieve_day',  :to => 'tasks#retrieve_day'
  match '/tasks/update',  :to => 'tasks#update'
  resources :tasks 
  match '/expenses/synchronize_with_mobile',  :to => 'expenses#synchronize_with_mobile'
  match '/expenses/synchronize_with_mobile_second_step',  :to => 'expenses#synchronize_with_mobile_second_step'
  match '/expenses/authenticate_mobile_user',  :to => 'expenses#authenticate_mobile_user'
  match '/expenses/copy_to_mobile',  :to => 'expenses#copy_to_mobile'
  match '/fix_user_id',  :to => 'expenses#fix_user_id'
  match '/expenses/shownew',  :to => 'expenses#shownew'
  match '/expenses/show1',  :to => 'expenses#show1'
  match '/expenses/getSubcategories',  :to => 'expenses#getSubcategories'
  match 'expenses/check_date_due', :to => 'expenses#check_date_due'
  resources :expenses 

end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  has_many  :expenses, :dependent => :destroy
  belongs_to :user
  belongs_to :category
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  # GET /subcategories
  # GET /subcategories.xml
  def index
    @subcategories = Subcategory.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @subcategories }
    end
  end

  # GET /subcategories/1
  # GET /subcategories/1.xml
  def show
    @subcategory = Subcategory.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @subcategory }
    end
  end

  # GET /subcategories/new
  # GET /subcategories/new.xml
  def new
    @subcategory = Subcategory.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @subcategory }
    end
  end

  # GET /subcategories/1/edit
  def edit
    @subcategory = Subcategory.find(params[:id])
  end

  # POST /subcategories
  # POST /subcategories.xml
  def create
    @subcategory = Subcategory.new(params[:subcategory])

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to(@subcategory, :notice => 'Subcategory was successfully created.') }
        format.xml  { render :xml => @subcategory, :status => :created, :location => @subcategory }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @subcategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /subcategories/1
  # PUT /subcategories/1.xml
  def update
    @subcategory = Subcategory.find(params[:id])

    respond_to do |format|
      if @subcategory.update_attributes(params[:subcategory])
        format.html { redirect_to(@subcategory, :notice => 'Subcategory was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @subcategory.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.xml
  def destroy
    @subcategory = Subcategory.find(params[:id])
    @subcategory.destroy

    respond_to do |format|
      format.html { redirect_to(subcategories_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/views/subcategories/_form.html.erb
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Category_code %><br />
    <%= f.text_field :Category_code %>
  </div>
  <div class="field">
    <%= f.label :subcategory_code %><br />
    <%= f.text_field :subcategory_code %>
  </div>
  <div class="field">
    <%= f.label :ttype %><br />
    <%= f.text_field :ttype %>
  </div>
  <div class="field">
    <%= f.label :enDescription %><br />
    <%= f.text_field :enDescription %>
  </div>
  <div class="field">
    <%= f.label :elDescription %><br />
    <%= f.text_field :elDescription %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subcategories/edit.html.erb
<h1>Editing subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory %> |
<%= link_to 'Back', subcategories_path %>

app/views/subcategories/index.html.erb
<h1>Listing subcategories</h1>

<table>
  <tr>
    <th>Category code</th>
    <th>Subcategory code</th>
    <th>Type</th>
    <th>Endescription</th>
    <th>Eldescription</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subcategories.each do |subcategory| %>
  <tr>
    <td><%= subcategory.category_code %></td>
    <td><%= subcategory.subcategory_code %></td>
    <td><%= subcategory.ttype %></td>
    <td><%= subcategory.enDescription %></td>
    <td><%= subcategory.elDescription %></td>
    <td><%= link_to 'Show', subcategory %></td>
    <td><%= link_to 'Edit', edit_subcategory_path(subcategory) %></td>
    <td><%= link_to 'Destroy', subcategory, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subcategory', new_subcategory_path %>

app/views/subcategories/new.html.erb
<h1>New subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path %>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category code:</b>
  <%= @subcategory.Category_code %>
</p>

<p>
  <b>Subcategory code:</b>
  <%= @subcategory.subcategory_code %>
</p>

<p>
  <b>Type:</b>
  <%= @subcategory.ttype %>
</p>

<p>
  <b>Endescription:</b>
  <%= @subcategory.enDescription %>
</p>

<p>
  <b>Eldescription:</b>
  <%= @subcategory.elDescription %>
</p>


<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %>