config/routes.rb
Todo::Application.routes.draw do 

  resources :categories

  resources :subcategories

  resources :expense_journals

  root :to => "home#index"
  match 'users/activateuser/:id', :to => 'users#activateuser'
  match '/users/:id/reset',  :to => 'users#updatepasswordreset'
  match '/signup/users/check_email', :to => 'users#check_email'
  match '/signup/users/check_name', :to => 'users#check_name'
  resources :users 
  resources :sessions, :only => [:new, :create, :destroy]
  get "sessions/new"
  match '/signup',  :to => 'users#new'
  match '/MailPasswordRequest',  :to => 'users#MailPasswordRequest'
  match '/MailPassword',  :to => 'users#MailPassword'
  match 'MailPassword/ResetPasswordRequest/:encryptedhash', :to => 'users#ResetPasswordRequest'
  match '/ResetPassword',  :to => 'users#ResetPassword'
  match '/ChangePasswordRequest',  :to => 'users#ChangePasswordRequest'
  match '/ChangePassword',  :to => 'users#ChangePassword'
  match '/DownloadMobile', :to => 'users#DownloadMobile'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/MapRequest',  :to => 'places#MapRequest'
  match '/MapOfPlace',  :to => 'places#MapOfPlace'
  match 'tasks/show',  :to => 'tasks#show'
  match 'tasks/show1',  :to => 'tasks#show1'
  match 'tasks/destroy',  :to => 'tasks#destroy'
  match '/signup/users/check_name', :to => 'users#check_name'
  match 'tasks/check_date_due', :to => 'tasks#check_date_due'
  match '/tasks/retrieve_day',  :to => 'tasks#retrieve_day'
  match '/tasks/update',  :to => 'tasks#update'
  resources :tasks 
  match '/expenses/synchronize_with_mobile',  :to => 'expenses#synchronize_with_mobile'
  match '/expenses/synchronize_with_mobile_second_step',  :to => 'expenses#synchronize_with_mobile_second_step'
  match '/expenses/authenticate_mobile_user',  :to => 'expenses#authenticate_mobile_user'
  match '/expenses/copy_to_mobile',  :to => 'expenses#copy_to_mobile'
  match '/fix_user_id',  :to => 'expenses#fix_user_id'
  match '/expenses/shownew',  :to => 'expenses#shownew'
  match '/expenses/show1',  :to => 'expenses#show1'
  match '/expenses/getSubcategories',  :to => 'expenses#getSubcategories'
  match 'expenses/check_date_due', :to => 'expenses#check_date_due'
  resources :expenses 

end

app/models/expense_journal.rb
class ExpenseJournal < ActiveRecord::Base
end

app/controllers/expense_journals_controller.rb
class ExpenseJournalsController < ApplicationController
  # GET /expense_journals
  # GET /expense_journals.xml
  def index
    @expense_journals = ExpenseJournal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @expense_journals }
    end
  end

  # GET /expense_journals/1
  # GET /expense_journals/1.xml
  def show
    @expense_journal = ExpenseJournal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @expense_journal }
    end
  end

  # GET /expense_journals/new
  # GET /expense_journals/new.xml
  def new
    @expense_journal = ExpenseJournal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @expense_journal }
    end
  end

  # GET /expense_journals/1/edit
  def edit
    @expense_journal = ExpenseJournal.find(params[:id])
  end

  # POST /expense_journals
  # POST /expense_journals.xml
  def create
    @expense_journal = ExpenseJournal.new(params[:expense_journal])

    respond_to do |format|
      if @expense_journal.save
        format.html { redirect_to(@expense_journal, :notice => 'Expense journal was successfully created.') }
        format.xml  { render :xml => @expense_journal, :status => :created, :location => @expense_journal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @expense_journal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /expense_journals/1
  # PUT /expense_journals/1.xml
  def update
    @expense_journal = ExpenseJournal.find(params[:id])

    respond_to do |format|
      if @expense_journal.update_attributes(params[:expense_journal])
        format.html { redirect_to(@expense_journal, :notice => 'Expense journal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @expense_journal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /expense_journals/1
  # DELETE /expense_journals/1.xml
  def destroy
    @expense_journal = ExpenseJournal.find(params[:id])
    @expense_journal.destroy

    respond_to do |format|
      format.html { redirect_to(expense_journals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/expense_journals_helper.rb
module ExpenseJournalsHelper
end

app/views/expense_journals/_form.html.erb
<%= form_for(@expense_journal) do |f| %>
  <% if @expense_journal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expense_journal.errors.count, "error") %> prohibited this expense_journal from being saved:</h2>

      <ul>
      <% @expense_journal.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :trxtype %><br />
    <%= f.text_field :trxtype %>
  </div>
  <div class="field">
    <%= f.label :trxdatetime %><br />
    <%= f.datetime_select :trxdatetime %>
  </div>
  <div class="field">
    <%= f.label :sn %><br />
    <%= f.text_field :sn %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :dateoccured %><br />
    <%= f.date_select :dateoccured %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :subcategory %><br />
    <%= f.text_field :subcategory %>
  </div>
  <div class="field">
    <%= f.label :exptype %><br />
    <%= f.text_field :exptype %>
  </div>
  <div class="field">
    <%= f.label :expmethod %><br />
    <%= f.text_field :expmethod %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/expense_journals/edit.html.erb
<h1>Editing expense_journal</h1>

<%= render 'form' %>

<%= link_to 'Show', @expense_journal %> |
<%= link_to 'Back', expense_journals_path %>

app/views/expense_journals/index.html.erb
<h1>Listing expense_journals</h1>

<table>
  <tr>
    <th>Trxtype</th>
    <th>Trxdatetime</th>
    <th>Sn</th>
    <th>Amount</th>
    <th>Dateoccured</th>
    <th>Category</th>
    <th>Subcategory</th>
    <th>Exptype</th>
    <th>Expmethod</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @expense_journals.each do |expense_journal| %>
  <tr>
    <td><%= expense_journal.trxtype %></td>
    <td><%= expense_journal.trxdatetime %></td>
    <td><%= expense_journal.sn %></td>
    <td><%= expense_journal.amount %></td>
    <td><%= expense_journal.dateoccured %></td>
    <td><%= expense_journal.category %></td>
    <td><%= expense_journal.subcategory %></td>
    <td><%= expense_journal.exptype %></td>
    <td><%= expense_journal.expmethod %></td>
    <td><%= link_to 'Show', expense_journal %></td>
    <td><%= link_to 'Edit', edit_expense_journal_path(expense_journal) %></td>
    <td><%= link_to 'Destroy', expense_journal, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Expense journal', new_expense_journal_path %>

app/views/expense_journals/new.html.erb
<h1>New expense_journal</h1>

<%= render 'form' %>

<%= link_to 'Back', expense_journals_path %>

app/views/expense_journals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Trxtype:</b>
  <%= @expense_journal.trxtype %>
</p>

<p>
  <b>Trxdatetime:</b>
  <%= @expense_journal.trxdatetime %>
</p>

<p>
  <b>Sn:</b>
  <%= @expense_journal.sn %>
</p>

<p>
  <b>Amount:</b>
  <%= @expense_journal.amount %>
</p>

<p>
  <b>Dateoccured:</b>
  <%= @expense_journal.dateoccured %>
</p>

<p>
  <b>Category:</b>
  <%= @expense_journal.category %>
</p>

<p>
  <b>Subcategory:</b>
  <%= @expense_journal.subcategory %>
</p>

<p>
  <b>Exptype:</b>
  <%= @expense_journal.exptype %>
</p>

<p>
  <b>Expmethod:</b>
  <%= @expense_journal.expmethod %>
</p>


<%= link_to 'Edit', edit_expense_journal_path(@expense_journal) %> |
<%= link_to 'Back', expense_journals_path %>