config/routes.rb
Todo::Application.routes.draw do 

  resources :categories

  resources :subcategories

  resources :expense_journals

  root :to => "home#index"
  match 'users/activateuser/:id', :to => 'users#activateuser'
  match '/users/:id/reset',  :to => 'users#updatepasswordreset'
  match '/signup/users/check_email', :to => 'users#check_email'
  match '/signup/users/check_name', :to => 'users#check_name'
  resources :users 
  resources :sessions, :only => [:new, :create, :destroy]
  get "sessions/new"
  match '/signup',  :to => 'users#new'
  match '/MailPasswordRequest',  :to => 'users#MailPasswordRequest'
  match '/MailPassword',  :to => 'users#MailPassword'
  match 'MailPassword/ResetPasswordRequest/:encryptedhash', :to => 'users#ResetPasswordRequest'
  match '/ResetPassword',  :to => 'users#ResetPassword'
  match '/ChangePasswordRequest',  :to => 'users#ChangePasswordRequest'
  match '/ChangePassword',  :to => 'users#ChangePassword'
  match '/DownloadMobile', :to => 'users#DownloadMobile'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/MapRequest',  :to => 'places#MapRequest'
  match '/MapOfPlace',  :to => 'places#MapOfPlace'
  match 'tasks/show',  :to => 'tasks#show'
  match 'tasks/show1',  :to => 'tasks#show1'
  match 'tasks/destroy',  :to => 'tasks#destroy'
  match '/signup/users/check_name', :to => 'users#check_name'
  match 'tasks/check_date_due', :to => 'tasks#check_date_due'
  match '/tasks/retrieve_day',  :to => 'tasks#retrieve_day'
  match '/tasks/update',  :to => 'tasks#update'
  resources :tasks 
  match '/expenses/synchronize_with_mobile',  :to => 'expenses#synchronize_with_mobile'
  match '/expenses/synchronize_with_mobile_second_step',  :to => 'expenses#synchronize_with_mobile_second_step'
  match '/expenses/authenticate_mobile_user',  :to => 'expenses#authenticate_mobile_user'
  match '/expenses/copy_to_mobile',  :to => 'expenses#copy_to_mobile'
  match '/fix_user_id',  :to => 'expenses#fix_user_id'
  match '/expenses/shownew',  :to => 'expenses#shownew'
  match '/expenses/show1',  :to => 'expenses#show1'
  match '/expenses/getSubcategories',  :to => 'expenses#getSubcategories'
  match 'expenses/check_date_due', :to => 'expenses#check_date_due'
  resources :expenses 

end

app/helpers/expenses_helper.rb
module ExpensesHelper

def insert_to_expenses_journal(operation, expense)
       	category_code = ''
	subcategory_code = ''
	category_code = Category.where(:id => expense.category).first.code
	if !expense.subcategory.nil? 
		subcategory_code = Subcategory.where(:id => expense.subcategory).first.subcategory_code
	else
	     	subcategory_code = ''
       	end

	@expense_journal = ExpenseJournal.new({:trxtype => operation, :trxdatetime => Time.now, :sn => expense.id, :amount => expense.amount, :dateoccured => expense.dateoccured, :category => category_code, :subcategory => subcategory_code, :exptype => expense.ttype, :expmethod =>expense.method, :user_id =>expense.user_id})
		@expense_journal.save

end

def get_mobile_updates(categoryrows, subCategoryrows, mobile_data, user_id)
	
  response = Array.new


#update Categories

    categorycode = ''
    categorytype = ''
    categoryenDescription = ''
    categoryelDescription = ''

  if !categoryrows.nil?
   categoryrows.each_index{|i|

    remainder = i % 4

    if remainder == 0
    	categorycode = categoryrows[i]
    end
    if remainder == 1
	categorytype = categoryrows[i]
    end
    if remainder == 2
	categoryenDescription = categoryrows[i]
    end
    if remainder == 3
	 categoryelDescription = categoryrows[i]
    	 @category = Category.find_by_user_id_and_code(user_id, categorycode)
	 if @category
		 @category.update_attributes(:code =>categorycode, :ttype => categorytype, :endescription => categoryenDescription, :eldescription => categoryelDescription, :updated_at => Time.zone.now, :user_id => user_id) 
	 else
		 @category = Category.new(:code =>categorycode, :ttype => categorytype, :endescription => categoryenDescription, :eldescription => categoryelDescription, :created_at => Time.zone.now, :updated_at => Time.zone.now, :user_id => user_id)
      		@category.save
	 end
    end
   }
  end

#update subCategories

    subCategorycode = ''
    subsubCategorycode = ''
    subCategorytype = ''
    subCategoryenDescription = ''
    subCategoryelDescription = ''
    category_id = ''	
    if !subCategoryrows.nil?
   subCategoryrows.each_index{|i|

    remainder = i % 5

    if remainder == 0
    	subCategorycode = subCategoryrows[i]
    end
    if remainder == 1
	subsubCategorycode = subCategoryrows[i]
    end
    if remainder == 2
	subCategorytype = subCategoryrows[i]
    end
    if remainder == 3
	subCategoryelDescription = subCategoryrows[i]
    end
    if remainder == 4
	subCategoryelDescription = subCategoryrows[i]
	category_id = Category.where('user_id = ? AND code = ?', user_id, subCategorycode).first.id
logger.debug "-----------------------------------------------#{category_id}"
#    	@subcategory = Subcategory.where('user_id = ? AND category_id = ? AND subcategory_code = ?', user_id, category_id, subsubCategorycode).first.id
	@subcategory = Subcategory.find_by_user_id_and_category_id_and_subcategory_code( user_id, category_id, subsubCategorycode)
	if @subcategory
		@subcategory.update_attributes(:category_id => category_id, :subcategory_code =>subsubCategorycode, :ttype => subCategorytype, :endescription => subCategoryenDescription, :eldescription => subCategoryelDescription, :updated_at => Time.zone.now, :user_id => user_id) 
	 else
		 @subcategory = Subcategory.new(:category_id =>category_id, :subcategory_code =>subsubCategorycode, :ttype => subCategorytype, :endescription => subCategoryenDescription, :eldescription => subCategoryelDescription, :created_at => Time.zone.now, :updated_at => Time.zone.now, :user_id => user_id) 
      		@subcategory.save
	 end 
    end
   }
  end



  trxtype = ''
  trxamount = 0
  trxdateOccured = 0
  trxcategory = ''
  trxsubcategory = '' 
  trxttype = ''
  trxmethod = ''
  trxmobileid = 0
  trxdatetime = ''
   category_id = '' 
  subcategory_id = '' 

# Additions
  if !mobile_data.nil?
   mobile_data.each_index{|i|

    remainder = i % 9

    if remainder == 0
    	trxtype = mobile_data[i]
    end
    if remainder == 1
	trxdatetime = mobile_data[i]
    end
    if remainder == 2
	trxmobileid = mobile_data[i]
    end
    if remainder == 3
    	trxamount = mobile_data[i]
    end
    if remainder == 4
    	trxdateOccured = mobile_data[i]
    end
    if remainder == 5
    	trxcategory = mobile_data[i]
    end
    if remainder == 6
    	trxsubcategory = mobile_data[i]
    end
    if remainder == 7
    	trxttype = mobile_data[i]
    end
    if remainder == 8
    	trxmethod = mobile_data[i]
    end 

    if (remainder == 8 and trxtype == 'A')
#    	@expense = Expense.new(:amount => trxamount, :dateoccured => trxdateOccured, :category => trxcategory, :subcategory => trxsubcategory, :ttype => trxttype, :method =>trxmethod, :mobileid =>trxmobileid, :created_at => Time.parse(trxdatetime).getutc, :updated_at => Time.parse(trxdatetime).getutc, :sync => "S")
#logger.debug "#{trxamount}"
#	logger.debug "#{trxcategory}"
#logger.debug "#{trxsubcategory}"
#logger.debug "#{trxttype}"
#logger.debug "#{trxmethod}"
#logger.debug "#{trxmobileid}"
	category_id =  Category.where('user_id = ? AND code = ?', user_id, trxcategory).first.id
	subcategory_id = Subcategory.where('user_id = ? AND category_id = ? AND subcategory_code = ?', user_id, category_id, trxsubcategory).first.id
	logger.debug "----------------------#{category_id}"
	logger.debug "----------------------#{subcategory_id}"
	@expense = Expense.new(:amount => trxamount, :dateoccured => trxdateOccured, :category_id => category_id, :subcategory_id => subcategory_id, :ttype => trxttype, :method =>trxmethod, :mobileid =>trxmobileid, :created_at => Time.zone.parse(trxdatetime), :updated_at => Time.zone.parse(trxdatetime), :sync => "S", :user_id => user_id)
logger.debug "#{@expense.amount}"
      if @expense.save
         response.push(@expense.mobileid, @expense.id)
	logger.debug "ooooooooooooooooooook"
      else
         response.push(@expense.mobileid, 0)
	logger.debug "ssssssssssssssssssssssssshit"
      end
    end
   }
  end


# Deletions
  if !mobile_data.nil?
   mobile_data.each_index{|i|

    remainder = i % 9

    if remainder == 0
    	trxtype = mobile_data[i]
    end
    if remainder == 1
	trxdatetime = mobile_data[i]
    end
    if remainder == 2
	trxmobileid = mobile_data[i]
    end
    if remainder == 3
    	trxamount = mobile_data[i]
    end
    if remainder == 4
    	trxdateOccured = mobile_data[i]
    end
    if remainder == 5
    	trxcategory = mobile_data[i]
    end
    if remainder == 6
    	trxsubcategory = mobile_data[i]
    end
    if remainder == 7
    	trxttype = mobile_data[i]
    end
    if remainder == 8
    	trxmethod = mobile_data[i]
    end 

    if (remainder == 8 and trxtype == 'D')
     @expense =  Expense.find_by_mobileid(trxmobileid)
	if @expense
#    logger.debug "#{Time.parse(trxdatetime).getutc}"
#    logger.debug "#{@expense.updated_at}"
	
#	   if @expense.updated_at < Time.parse(trxdatetime).getutc
		if @expense.destroy
#   		      response.push(@expense.mobileid, @expense.id)
      		else
#         	      response.push(@expense.mobileid, 0)
		end
#	   end

	end
    end
   }
  
  end 

  # Updates
  if !mobile_data.nil?
   mobile_data.each_index{|i|

    remainder = i % 9

    if remainder == 0
    	trxtype = mobile_data[i]
    end
    if remainder == 1
	trxdatetime = mobile_data[i]
    end
    if remainder == 2
	trxmobileid = mobile_data[i]
    end
    if remainder == 3
    	trxamount = mobile_data[i]
    end
    if remainder == 4
    	trxdateOccured = mobile_data[i]
    end
    if remainder == 5
    	trxcategory = mobile_data[i]
    end
    if remainder == 6
    	trxsubcategory = mobile_data[i]
    end
    if remainder == 7
    	trxttype = mobile_data[i]
    end
    if remainder == 8
    	trxmethod = mobile_data[i]
    end 

 
    if (remainder == 8 and trxtype == 'U')
      @expense =  Expense.find_by_mobileid(trxmobileid)
	if @expense 
#     logger.debug "#{Time.zone}"
#     logger.debug "#{Time.parse(trxdatetime)}"
    logger.debug "#{@expense.updated_at}"
     logger.debug "#{Time.zone.parse(trxdatetime)}"
	   if @expense.updated_at < Time.zone.parse(trxdatetime)
		category_id = Category.where('user_id = ? AND code = ?', user_id, trxcategory).first.id
		subcategory_id = Subcategory.where('user_id = ? AND category_id = ? AND subcategory_code = ?', user_id, category_id, trxsubcategory).first.id
#		if @expense.updated_at < Time.parse(trxdatetime).getutc
		if @expense.update_attributes(:amount => trxamount, :dateoccured => trxdateOccured, :category_id => category_id, :subcategory_id => subcategory_id, :ttype => trxttype, :method =>trxmethod, :mobileid =>trxmobileid, :updated_at => Time.zone.parse(trxdatetime), :sync => "S") 
#   		      response.push(@expense.mobileid, @expense.id)
      		else
#         	      response.push(@expense.mobileid, 0)
		end
	   end
	end
    end

   }
  end


  @expense_journal = ExpenseJournal.all
  @expense_journal = ExpenseJournal.where(:user_id => user_id)
  #  if !@expense_journal.nil?
  unless @expense_journal.empty?
      response.push('web')
#     logger.debug "#{@expense_journal}"
    @expense_journal.each do |expense|
   	response.push(expense.trxtype, expense.trxdatetime.to_formatted_s(:db), expense.sn, expense.amount, expense.dateoccured.to_formatted_s(:db).gsub!('-','/'), expense.category, expense.subcategory, expense.exptype, expense.expmethod)
#         response.push(expense.trxtype, expense.trxdatetime, expense.sn, expense.amount, expense.dateoccured.to_formatted_s(:db).gsub!('-','/'), expense.category, expense.subcategory, expense.exptype, expense.expmethod)
         expense.destroy
    end 
  end 

  return response

 end

 def get_mobile_updates_second_step(mobile_data_2)
 # Update mobile_id
  logger.debug "#{mobile_data_2}"

  webid = 0

  if !mobile_data_2.nil?
   mobile_data_2.each_index{|i|

    remainder = i % 2

    if remainder == 0
    	webid = mobile_data_2[i]
    end
    if remainder == 1
	mobid = mobile_data_2[i]
#	if Expense.exists?(webid)
#	   @expense =  Expense.find(webid)

app/views/expenses/_addExpenseForm.html.erb
<%=  form_for @expense, :as => :expense, :url => { :action => "create" }, :html => { :id => "newexpense" }, :remote => true do |f| %> 
   <%= f.text_field :amount, :size => 8, :placeholder => t(:Enter_expense_amount),  :maxlength => 10 %>
   <%= f.text_field :dateoccured, :size => 10, :value => l(Date.current, :format => :default), :maxlength => 10 %>
   <%= f.collection_select :category_id, Category.where(:user_id => current_user), :id, :elDescription, {}, {:id=>'add-expense-category'}%>
   <!-- %= f.collection_select :category_id, Category.all, :id, :elDescription% -->
   <!--%= f.collection_select :category_id, Category.all, :id, :elDescription, :prompt => "Category" % -->
   <!-- %= f.collection_select :category_id, @categories, :id, :elDescription, :prompt => "Category" % -->
   <!-- % if @subcategories.blank? % -->
   <!-- % else % -->
	 <!-- %= f.collection_select :subcategory_id, $subcategories, :id, :elDescription, :prompt => "Subcategory" % -->
	 <%= f.collection_select :subcategory_id, Subcategory.where(:category_id => Category.where(:user_id => current_user).first), :id, :elDescription, {}, {:id=>'add-expense-subcategory'}%>
  <!-- % end % -->
   <%= f.select(:method, options_for_select([[t(:Cash),"M"],[t(:Card),"C"]])) %>
   <%= f.submit t(:Add_task) %>
<% end %>

app/views/expenses/_addexpense.html.erb
<tr CLASS="gridtable">
      <td CLASS="id" style="display: none"><%= @expense.id %></td>
      <td CLASS="expamount" id="expamount"><%= @expense.amount %></td>
      <td CLASS="originaldateOccured" id="expdate"><%= @day[@expense.dateoccured.wday] + " " + @expense.dateoccured.strftime("%d") + "/" +@expense.dateoccured.strftime("%m")+ "/" +@expense.dateoccured.strftime("%y") %></td>
      <td CLASS="expcategory" id="expcategory"><%= @expense.category.elDescription %></td>
      <% if @expense.subcategory.nil? %>
	  <td CLASS="expsubcategory" id="expsubcategory"><%= " " %></td>
      <%else %>      
          <td CLASS="expsubcategory" id="expsubcategory"><%= @expense.subcategory.elDescription %></td>
      <% end %>
      <td CLASS="expmethod" id="expmethod"><%= @expense.method %></td>
      <td CLASS="prior editexpense"><%= link_to (image_tag 'ico_edit.png'), edit_expense_path(@expense), :remote => true %></td>
      <td CLASS="prior destroyexpense"><%= link_to (image_tag 'ico_delete.png'), @expense, :confirm => t(:Are_you_sure?), :method => :delete, :remote => true %></td>
</tr>

app/views/expenses/autocomplete.js.erb
$('#notasks').addClass('hidden');
$('#paginate').hide();
$('#paginateautocomplete').show();
$('#tbl').empty().append("<%= escape_javascript(render(:partial => 'tasks/autocompletetasks')) %>");

// <link rel="stylesheet" type="text/css" href="./stylesheets/blueprint/screen.css">
$(function() {
            var tr = $('#tbl').find('tr');
	    tr.hover(
                  a=function() {  // mouseover
//                    previous.removeClass('row-highlight');
		    $('#task-details').addClass('task-info'); 
                    $(this).removeClass('gridtable');
                    $(this).addClass('row-highlight');
		    $(this).addClass('active-row');
                     var values = '';
                     var tds = $(this).find('td');

                     $.each(tds, function(index, item) {
//                         values = values + 'td' + (index + 1) + ':' + item.innerHTML + '<br/>';
	 			if (index==2) {values = values + I18n.t("javascripts.Description") + item.innerHTML + '<br/>';}
  				if (index==3) {values = values + I18n.t("javascripts.Due") + item.innerHTML + '<br/>';}
  				if (index==4) {values = values + I18n.t("javascripts.Priority") + item.innerHTML + '<br/>';}
  				if (index==7) {values = values + I18n.t("javascripts.type") + item.innerHTML + '<br/>';}
  				if (index==8) {values = values + I18n.t("javascripts.status") + item.innerHTML + '<br/>';}
  				if (index==9) {values = values + I18n.t("javascripts.status_date") + item.innerHTML + '<br/>';}
  				if (index==10) {values = values + I18n.t("javascripts.budget") + item.innerHTML + '<br/>';}
  				if (index==11) {values = values + I18n.t("javascripts.long_description") + '<br/><textarea class="txtarea">' + item.innerHTML + '</textarea>';
						$('#txt').css("color","red");}
                     });
                     $('#task-details').html(values);
                 },
                  b=function() {  // mouseout
		    $('#task-details').removeClass('task-info'); 
		     $(this).removeClass('row-highlight');
		     $(this).removeClass('active-row');
//  		     $("#tbl tr:nth-of-type(even)").addClass('gridtable');
  		     $(this).addClass('gridtable');
                     $('#task-details').html('');
                 }
            );
});

//$("#tbl").delegate('click', '.edit a', c=function(event){
$(".edit a").bind('click', c=function(event) {
//$(".edit a").click(c=function (event) {
		event.preventDefault();
		var oldDesc;
		var olddDue;
		var oldPriority;
                 var tr = $('#tbl').find('tr');
		 tr.unbind('mouseenter').unbind('mouseleave');
		 $("#task_due").attr('disabled', 'disabled');
		 $("#task_description").attr('disabled', 'disabled');
		 $("#task_priority").attr('disabled', 'disabled');
	//	 tr.removeClass('row-highlight');
	//		 if bluerow == true {tr.addClass('gridtable');}	
		 $(".edit a").unbind('click');
	//	 $("a").click(function(){return false;})


                     var tds = $('tr.active-row').find(' td');

                     $.each(tds, function(index, item) {
	 			if (index==2) {oldDescription = item.innerHTML;}
  				if (index==12) {oldDue = item.innerHTML;}
  				if (index==4) {oldPriority = item.innerHTML;}
  				if (index==7) {oldType = item.innerHTML;}
  				if (index==8) {oldStatus = item.innerHTML;}
  				if (index==9) {oldStatusDate = item.innerHTML;}
  				if (index==10) {oldBudget = item.innerHTML;}
  				if (index==11) {oldLongDescription = item.innerHTML;}
                     });

		  
		 var href = $(this).attr('href');
		 var i1 = href.indexOf("tasks");
		 var i1 = i1 + 6;
		 var i2 = href.indexOf("edit");
		 var i2 = i2 - 1;
		 var taskid = href.slice(i1, i2);
		 var values = ''; 
		 $('#task-details').addClass('task-info'); 
		  values = values + '<form accept-charset="UTF-8" action="/tasks/update" class="task_edit" data-remote="true" id="edit_task" method="post">';
		  values = values + '<input id="task_id" name="task[id]" value=' + taskid + ' type="hidden" />';
		  values = values + '<div class="rowLayout">';
		 values = values + '<label for="task[description]">'+I18n.t("javascripts.Description")+'</label>';  
		  values = values + '<input id="task_description" maxlength="30" name="task[description]" size="30" type="text" value ="' + oldDescription + '" />';
		 values = values +  '</div>';
		  values = values + '<div class="rowLayout">';
		 values = values + '<label>'+I18n.t("javascripts.Due")+'</label>'; 
  		  values = values + '<input id="task_due1" readonly="true" class="datepicker" maxlength="10" name="task[due]" size="10" type="text" value ="' + oldDue + '" />';
		 values = values +  '</div>';
		  values = values + '<div class="rowLayout">';
		 values = values +  '<label>'+I18n.t("javascripts.Priority")+'</label>';
		  values = values + '<input id="task_priority" maxlength="1" name="task[priority]" size="1" type="text" value ="' + oldPriority + '" />';
		 values = values +  '</div>';
		  values = values + '<div class="rowLayout">';
		 values = values +  '<label>'+I18n.t("javascripts.type")+'</label>';
		  values = values + '<input id="task_ttype" maxlength="1" name="task[ttype]" size="1" type="text" value ="' + oldType + '" />';
		 values = values +  '</div>';
		  values = values + '<div class="rowLayout">';
		 values = values +  '<label>'+I18n.t("javascripts.status")+'</label>';
		  values = values + '<input id="task_status" maxlength="1" name="task[status]" size="1" type="text" value ="' + oldStatus + '" />';
		 values = values +  '</div>';
		  values = values + '<div class="rowLayout">';
		 values = values +  '<label>'+I18n.t("javascripts.status_date")+'</label>';
		  values = values + '<input id="task_status_date" maxlength="10" name="task[status_date]" size="10" type="text" value ="' + oldStatusDate + '" />';
		 values = values +  '</div>';
		  values = values + '<div class="rowLayout">';
		 values = values +  '<label>'+I18n.t("javascripts.budget")+'</label>';
		  values = values + '<input id="task_budget" maxlength="11" name="task[budget]" size="11" type="text" value ="' + oldBudget + '" />';
		 values = values +  '</div>';
		  values = values + '<div class="rowLayout">';
		 values = values +  '<label>'+I18n.t("javascripts.long_description")+'</label>';
		  values = values + '<textarea id="task_long_description" class="txtarea" maxlength="100" name="task[long_description]" size="100">' + oldLongDescription + '</textarea>';
		 values = values +  '</div>';
                 values = values + '<input id="task_submit" name="commit" type="submit" value="Update" />';
		  values = values + '</form>';

		  $('#task-details').empty().html(values);
	  	  //	 $("#tbl").undelegate('click', '.edit a', c);
//                 var id = $(this).attr('href');
	//		 $('#task-details').empty().load(id, function()
	//                 {$('#description').focus();});
	//	 $('#task-details').empty().load(id);
});

app/views/expenses/edit.js.erb
$('#expense-details').addClass('expense-info'); 
$('#expense-details').html("<%= escape_javascript(render :partial => "updateExpenseForm") %>");
$(".editexpense a").on('click', c=function(event) {
		var oldexpamount;
		var oldoriginaldateOccured;
		var oldexpcategory;
		var oldexpsubcategory;
		var oldexpmethod;
                 var tr = $('#tbl').find('tr');
		 tr.unbind('mouseenter').unbind('mouseleave');
		 $("#expense_amount").attr('disabled', 'disabled');
		 $("#expense_dateoccured").attr('disabled', 'disabled');
		 $("#expense_category_id").attr('disabled', 'disabled');
		 $("#expense_subcategory_id").attr('disabled', 'disabled');
		 $("#expense_method").attr('disabled', 'disabled');
		 $(".editexpense a").off('click');
                     var tds = $('tr.active-row').find(' td');
                     $.each(tds, function(index, item) {
	 			if (index==2) {oldexpamount = item.innerHTML;}
  				if (index==12) {oldoriginaldateOccured = item.innerHTML;}
  				if (index==4) {oldexpcategory = item.innerHTML;}
  				if (index==7) {oldexpsubcategory = item.innerHTML;}
  				if (index==8) {oldexpmethod = item.innerHTML;}
                    });
});

app/views/expenses/exportToExcel.html.erb
<%= link_to 'Export XLS', url_for(:format => 'xls') %>

app/views/expenses/getChartdata.js.erb
$('#noexpenses').addClass('hidden');

pre>
  <%= @barchartdata.inspect %>
</pre>

<table id="tbl">
<!-- col style="{visibility: collapse;}" / -->

<% @barchartdata.each do |index, barchartdata| %>
    <tr>
      <td><%=  barchartdata [index] %></td>
   </tr>
  <% end %>
</table>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Amount:</b>
  <%= @expense.amount %>
</p>

<p>
  <b>Dateoccured:</b>
  <%= @expense.dateoccured %>
</p>

<p>
  <b>Category:</b>
  <%= @expense.category %>
</p>

<p>
  <b>Subcategory:</b>
  <%= @expense.subcategory %>
</p>

<p>
  <b>Type:</b>
  <%= @expense.ttype %>
</p>

<p>
  <b>Method:</b>
  <%= @expense.method %>
</p>

<p>
  <b>Created_at:</b>
  <%= @expense.created_at %>
</p>


<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/show.js.erb
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>

<%= javascript_include_tag 'tasklistview' %>  

<script type="text/javascript">


$(".pagination a").click(function (event) {
    		 event.preventDefault();
		 var id = $(this).attr('href');
		 $('#task_information').empty().load(id);
       		 $('#task-details').empty();
});



$(document).ready(function() {
	//		$( "#tab-container" ).bind( "tabsselect", function() {
			$('#task-details').removeClass('task-info'); 
			$('#task-details').empty();
			$('#paginate').show();
			$('#paginateautocomplete').hide();

});


</script>

<table id="tbl">
<!-- col style="{visibility: collapse;}" / -->
<% @tasks.each do |task| %>
    <tr CLASS="gridtable">
      <td CLASS="id" style="display: none"><%= task.id %></td>
      <td CLASS="originaldue" style="display: none"><%= task.due.to_s[0,10] %></td>
      <td CLASS="desc" id="desc"><%= task.description %></td>
      <td CLASS="due" id="due"><%= @day[task.due.wday] + " " + task.due.strftime("%d") + "/" + task.due.strftime("%m")+ "/" + task.due.strftime("%y") %></td>
      <td CLASS="prior" id="prior"><%= task.priority %></td>
      <td CLASS="prior edit"><%= link_to t(:Edit), edit_task_path(task) %></td>
      <td CLASS="prior destroy"><%= link_to t(:Destroy), task, :confirm => t(:Are_you_sure?), :method => :delete, :remote => true %></td>
      <td CLASS="ttype" id="ttype" style="display: none"><%= task.ttype %></td>
      <td CLASS="status" id="status" style="display: none"><%= task.status %></td>
      <td CLASS="status_date" id="status_date" style="display: none"><%= task.status_date %></td>
      <td CLASS="budget" id="budget" style="display: none"><%= task.budget %></td>
      <td CLASS="long_description" id="long_description" style="display: none"><%= task.long_description %></td>
      <td CLASS="olddue" id="olddue" style="display: none"><%= task.due.strftime("%d") + "/" + task.due.strftime("%m")+ "/" + task.due.strftime("%Y") %></td>
   </tr>
  <% end %>
</table>

<div id="paginate">
<%= will_paginate @tasks %>
</div>
 <!-- %= will_paginate @tasks, :renderer => RemoteLinkRenderer % -->